### ISSUE TITLE
Setup Repositorys

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#1]
**Task title**
Set up Repository

**Task description**
This task involves setting up a new repository. Below are the details of the subtasks :

**Subtasks**
- [x] Update the README with the necessary information.
- [x] Modify repository settings according to the project's requirements.
- [x] Protect the `develop` and `main` branches to prevent accidental changes.
- [x] Add component folders
- [x] upgrade nextjs to the latest version
  
**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/af237630-4407-42d7-b943-354e449f4754)

**Comment by DigitalDeveloperAM** [comment]
This pull request has been checked, Everything running smooth with all features.
