### ISSUE TITLE
style the coupons page banner

### ISSUE THREAD

**Issue by HamidAhmidat** [202306-NEA-DZ-FEW/team-five#100]
**Task title**
style the coupons page banner

**Task description**
in this issue Im going to style the banner to be responsive and identical to the figma design 

**Subtasks**

- [x] add a section which will contain the banner
- [x] add an image 
- [x] add a description to the banner
- [ ] add details to the description

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/137908128/9fc9b63f-66aa-42ac-9496-0f2b50171e6c)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2475-3133&mode=design&t=oMKC1lWN6ZYEcfYU-4
