### ISSUE TITLE
Fix Food Image Problem Blocking Clone and Pull

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#102]
**Issue title**
Fix Food Image Problem Blocking Clone and Pull

**Issue description**
There is a problem with the food images in the project repository that is causing issues during the cloning and pulling processes. This issue is created to address and resolve the problem, making it easier for users to clone and pull the project.

**Tasks**
- [x] Identify the specific issue related to food images that is blocking cloning and pulling
- [x] Review and optimize the storage and handling of food images in the project repository
- [x] Remove or replace problematic image files
- [x] Test the cloning and pulling processes to confirm that the issue has been resolved

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/ad9bdb95-c149-40bd-be4c-3db767032df8)
