### ISSUE TITLE
Fix Newsletter Component with Pop-up and Cookie Control

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#105]
**Task title**
Fix Newsletter Component with Pop-up and Cookie Control

**Task description**
Develop a newsletter subscription component that displays as a pop-up after a delay of 30 seconds. Additionally, implement cookie control to ensure that the pop-up is shown to users only once a day.

**Subtasks**
- [x] Design the newsletter component's user interface
- [x] Implement a timer to display the pop-up after 30 seconds of user interaction
- [x] Integrate cookie management to track and control pop-up display
- [x] Ensure that the pop-up respects the "once a day" rule based on cookies
- [x] Add options for users to subscribe or dismiss the newsletter
- [x] Test the pop-up functionality to ensure it works as expected
- [x] select the Newsletter show randomly 

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/b2695847-5d18-42c7-a1a8-4a472a53d5b4)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2311-4055&mode=design&t=8rXzOjxuUXv1Tssm-4
