### ISSUE TITLE
translate to the coupons page

### ISSUE THREAD

**Issue by HamidAhmidat** [202306-NEA-DZ-FEW/team-five#115]
**Task title**
translate to the coupons page

**Task description**
this issue will tackle the whole page and it will make major changes to the translation part.

**Subtasks**

- [x] translate the banner header and the details
- [x] translate the header of the coupons card
- [x] translate the card and its details

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/137908128/d619324e-e5f5-4d63-916b-13d6b7d9299b)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2475-3133&mode=design&t=FpjeB9nXMlji8dl4-4
