### ISSUE TITLE
Fix Footer Text Placement and Responsiveness

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#120]
**Issue title**
Fix Footer Text Placement and Responsiveness

**Issue description**
The current footer is experiencing issues with text placement and responsiveness. This issue is created to address and resolve the problems, ensuring that the footer displays correctly and is responsive on various devices and screen sizes.

**Tasks**
- [x] Review the styling code for the footer
- [x] Change footer Green color and blue make it same as Navbar
- [x] Remove 2023 (there's 2)
- [x] Implement solutions to fix the text placement and make the footer responsive
- [x] Test the footer on different devices and screen sizes to confirm that the issues have been resolved

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/396e940c-8001-493f-9098-c2bd0f8bff03)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=3179-3416&mode=design&t=f1KiupjARESpwDKt-4
