### ISSUE TITLE
Set Up Jest Mocks for Testing

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#122]
**Task title**
Set Up Jest Mocks for Testing

**Task description**
Configure Jest to use mocks for testing in the project. Setting up mocks helps isolate components and dependencies for more controlled and efficient testing.

**Subtasks**
- [x] Review the project's testing requirements and dependencies that need to be mocked
- [x] Create mock modules or functions for external dependencies
- [x] Configure Jest to use these mocks during testing
- [x] Write test cases that use the configured mocks
- [x] Test the project to ensure that mocks are working as expected and providing accurate results
