### ISSUE TITLE
stories component

### ISSUE THREAD

**Issue by DigitalDeveloperAM** [202306-NEA-DZ-FEW/team-five#127]
**Task title**
Stories component for blog page

**Task description**

- [x] Design and responsive
- [x] Adding the component to the blog page
- [x] fixing bugs in the blog page

**Screenshots**
![stories](https://github.com/202306-NEA-DZ-FEW/team-five/assets/107757609/31f61cbe-d125-483d-9227-9d9977a6449c)
