### ISSUE TITLE
Set up Vercel CI/CD for Deployment

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#13]
**Task title**
Set up Vercel CI/CD for Deployment

**Task description**
We need to set up a Continuous Integration and Continuous Deployment (CI/CD) pipeline with Vercel to automate the deployment process for our project. This will help ensure that changes are deployed seamlessly and reliably.

**Subtasks**
- [x] Set up Vercel account
- [x] Configure Vercel project settings
- [x] Integrate CI/CD workflow with GitHub Actions
- [x] Test the CI/CD

**Comment by Zino0031** [comment]
Done
