### ISSUE TITLE
Add Loading GIF

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#138]
**Task title**
Add Loading GIF

**Task description**
Enhance the user experience by incorporating a loading GIF to indicate ongoing processes or content loading within the application.

**Subtasks**
- [x] Select or create a suitable loading GIF for the project
- [x] Integrate the loading GIF in relevant sections where loading or processing occurs
- [x] Ensure the loading GIF is displayed appropriately and consistently
- [x] Test the loading GIF in different scenarios to confirm it aligns with the user experience

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/20d7e6fb-c6e2-4d6f-a83f-cd4b07a4f5fc)

**Link to the component on Figma**
(https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=0-1&mode=design)
