### ISSUE TITLE
Create Button Component

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#14]
**Task title**
Create Button Component

**Task description**
Design and implement a reusable button component

**Subtasks**
- [ ] Design button styles
- [ ] Implement button functionality
- [ ] Test the button component

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/d66b87a4-2053-432a-bfaf-4b7314fde965)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2430-5593&mode=design&t=LeCmaybhTbqQXYZh-4
