### ISSUE TITLE
Fix Authentication Page Design

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#140]
**Task title**
Fix Authentication Page Design

**Task description**
Enhance the authentication page by addressing design issues and improving its visual appearance for a better user experience.

**Subtasks**
- [x] Review the current design of the authentication page to identify specific areas that need improvement
- [x]  style of the authentication page for a more visually pleasing appearance
- [x] fix responsive design
- [x] Test the authentication page design to confirm that the changes align with the intended user experience

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/1e24e4c7-fe4d-4ce3-a95d-fa8e5b7cc7dc)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2545-3375&mode=design&t=N5GIdzkP5SojE9yo-4
