### ISSUE TITLE
Team Slider Component

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#15]
**Task title**
Team Slider Component

**Task description**
Create a team slider component that allows displaying team members' information and images in a carousel or slider format.

**Subtasks**
- [x] Design slider interface
- [x] Add cards to slider
- [x] Implement slider functionality
- [ ] Test the team slider component

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/384de002-37c5-4898-a364-f63a183e7a54)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2432-5600&mode=design&t=LeCmaybhTbqQXYZh-4
