### ISSUE TITLE
Create Team Card Component

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#16]
**Task title**
Create Team Card Component

**Task description**
Implement a component for displaying information about team members in a card format.

**Subtasks**
- [x] Design team card layout
- [x] Implement card functionality
- [ ] Test the team card component

**Screenshots**

> ![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/df813def-e336-4a35-8d50-094bc2aa9fb1)

**Link to the component on Figma**

https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2321-5594&mode=design&t=LeCmaybhTbqQXYZh-4
