### ISSUE TITLE
Generate Random Coupon Number and Add to Firebase

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#161]
**Task title**
Generate Random Coupon Number and Add to Firebase

**Task description**
Implement a feature to generate a random coupon number and store it in Firebase for use in the application.

**Subtasks**
- [x] Develop a function to generate a random coupon number
- [x] Integrate the function into the application's logic
- [x] Set up a connection to Firebase for storing coupon numbers
- [x] Implement code to add the generated coupon number to Firebase
- [x] Test the functionality to ensure coupon numbers are generated and stored correctly

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/29063b4c-6d5e-4305-a48a-8f06d3c6b09a)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=0-1&mode=design
