### ISSUE TITLE
Create Admin Coupons Page

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#165]
**Task title**
Create Admin Coupons Page

**Task description**
Develop an admin page specifically for managing coupons. This page will provide administrative functionalities such as viewing, adding, editing, and deleting coupons.

**Subtasks**
- [x] Design the layout and structure of the admin coupons page
- [x] Set up necessary routing for the new admin page (e.g., `/admin/coupons`)
- [x] Develop components for listing existing coupons
- [x] Implement a form for adding new coupons
- [x] Integrate functionality for editing existing coupons from firebase
- [x] Add filter to show each company her coupons
- [x] Add filter with amount select
- [x] Implement actions for deleting coupons and also delete from firebase
- [x] Test the admin coupons page to ensure all functionalities work as expected

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/3ea3913f-3478-4007-834c-1b16de2457a9)

**Link to the component on Figma**

https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=3478-3603&mode=design&t=FiqmS2Am4iaNWZNZ-4
