### ISSUE TITLE
Fix Bugs

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#179]
**Issue title**
Fix Bugs

**Subtasks**
- [x] Change coupon banner image to a higher quality image
- [x] Change coupon admin card to use an image
- [x] Fix translation issues in the admin section
- [x] Resolve translation problems in the cart section
- [x] Resolve the issue where the language selection remains unchanged after switching
- [x] Fix language-related images on routing pages
- [x] Update social share links to use environment variables
- [x] Resolve loading issues on dynamic pages
- [x] Ensure admin/coupons page is responsive across different devices
- [x] Fix Feedback form to send emails

**Task description**
This issue aims to fix several identified bugs in different areas of the project. Each subtask addresses a specific issue that needs to be resolved.
