### ISSUE TITLE
Receive updates on Blog and Events by email

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#18]
**Task title**
Receive updates on Blog and Events by email

**Task description**
Implement a feature that allows users to subscribe to email notifications for blog updates and event announcements. 

**Subtasks**
- [ ] Create an email subscription system
- [ ] Allow users to manage their email notification preferences
- [ ] Send email notifications for new blog posts
- [ ] Send email notifications for upcoming events
- [ ] Test Component 

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/f0f0875d-454b-4c65-b6cc-e51f61ab79ee)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2321-5509&mode=design&t=LeCmaybhTbqQXYZh-4
