### ISSUE TITLE
fix homePage bugs

### ISSUE THREAD

**Issue by HamidAhmidat** [202306-NEA-DZ-FEW/team-five#182]
**Task title**
fix homePage bugs

**Task description**
fix all the bugs in the homePage

**Subtasks**

- [ ] fix sponsors responsiveness 
- [x] fix buttons responsivness
- [x] add a link to the join us button
- [ ] restyle the subscribe blogs button

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/137908128/c63f7121-928a-4157-9c53-257fae3c82b0)

**Link to the component on Figma**
no figma link needed
