### ISSUE TITLE
Create Navbar Component

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#2]
**Task title**
Create Navbar Component

**Task description**
Design, create, and implement a responsive Navbar component for the project, including navigation links and any necessary functionality.

**Subtasks**
- [x] Design the Navbar layout
- [x] Implement responsive design
- [x] Add navigation links

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/f86e1145-f252-4418-b2b7-295092ca45c9)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2321-4625&mode=design&t=X0wIFiJmCxZf78tw-4
