### ISSUE TITLE
Create Sign-up Page

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#24]
**Task title**
Create Sign-up Page

**Task description**
Design and implement a user sign-up page for the project. This sign-up page will allow new users to register for accounts.

**Subtasks**
- [x] Design the sign-up page UI
- [x] Implement user registration functionality
- [x] Create a login link or button for existing users (if applicable)
- [x] Add Google Register
- [x] Test the sign-up page with various registration scenarios

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/0e524667-7a41-48c5-b3b5-e44c5db4d892)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2545-3750&mode=design&t=QvZdAVGqOh1JmONM-4
