### ISSUE TITLE
Create Sign-in Page

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#26]
**Task title**
Create Sign-in Page

**Task description**
Design and implement a user sign-in page for the project. This sign-in page will allow existing users to log in to their accounts.

**Subtasks**
- [ ] Design the sign-in page UI
- [ ] Implement user authentication and sign-in functionality
- [ ] Create a link or button for user registration

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/76a62c76-093b-4458-b1ee-45c6cdf642b1)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2545-3375&mode=design&t=QaX1NnjGQVofsfXw-4
