### ISSUE TITLE
Create Email Confirmation Page

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#29]
**Task title**
Create Email Confirmation & Password change Page

**Task description**
Design and implement an email confirmation page and Password change for the project. This page will be used to confirm and verify users' email addresses after registration.

**Subtasks**
- [x] Design the email confirmation page UI
- [x] Password change 
- [x] Implement email confirmation functionality
- [x] Generate and send confirmation emails to users
- [x] Generate and send users Password change emails 
- [x] Test the email confirmation process
