### ISSUE TITLE
Create Chart Component

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#31]
**Task title**
Create Chart Component 

**Task description**
Design and implement a chart component that visually represents the usage of coupons in our system. This chart should provide insights into the number of coupons used over a specific time period.

**Subtasks**
- [ ] Design the chart component's UI and layout
- [ ] Develop the chart component to retrieve and visualize coupon usage data
- [ ] Allow customization of the time period and other chart parameters
- [ ] Test the chart component with sample data

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/aebc9d98-ed51-46bd-a664-fb924ae5b067)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2311-1464&mode=design&t=JvU978mB3N0hGLoK-4
