### ISSUE TITLE
Create Used Coupons Info Cards

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#33]
**Task title**
Create Used Coupons Info Cards

**Task description**
Design and implement info cards to display detailed information about used coupons. These info cards will provide essential data and statistics related to the utilization of coupons.

**Subtasks**
- [x] Design the layout and style of the info cards
- [x] Develop the info card components to retrieve and display coupon information
- [x] Define the data and statistics to be shown on the cards
- [x] Test the info cards with sample data

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/bf9e2725-86c3-4fcf-a739-4d5cb3e3a841)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2311-1464&mode=design&t=yacxthhS8alUPMtj-4
