### ISSUE TITLE
Creating Blog page

### ISSUE THREAD

**Issue by DigitalDeveloperAM** [202306-NEA-DZ-FEW/team-five#35]
**Task title**
Creating Blog page

**Task description**
Creating Blog page that hold all the blogs that created by members.

**Subtasks**
- [x] Add blog page with navigation link.
- [x] Creating Hero image with text and add donation button.
- [ ] Add blog card that hold the fetch data.

**Screenshots**
![blog](https://github.com/202306-NEA-DZ-FEW/team-five/assets/107757609/b8b670cd-b0c5-4aac-9234-bba9974f15e4)

**Link to the component on Figma**
[Put the link here](https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2426-4592&mode=design&t=tkIHQjkzJQlnZ24S-4)
