### ISSUE TITLE
Create a Banner Component

### ISSUE THREAD

**Issue by HamidAhmidat** [202306-NEA-DZ-FEW/team-five#37]
**Task title**
Create a Banner Component 
**Task description**
create a reusable banner component to be used in the needed pages.

**Subtasks**

- [x] Design the layout and style of the banner.
- [x] the banner must be responsive in all the screens.
- [ ] create a test for the banner.

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/137908128/9c9a18c8-0f3a-4879-97a1-06a92fe62820)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2430-5596&mode=design&t=4oQohvyx5sYpOT4W-4
