### ISSUE TITLE
The Blog card component

### ISSUE THREAD

**Issue by DigitalDeveloperAM** [202306-NEA-DZ-FEW/team-five#44]
**Task title**
The blog card component

**Task description**
Create the component of the blog card that has the blog image, and the author and date, short description of the blog, and link to the blog post.

**Subtasks**

- [x]  Design the card.
- [x] Add blog image.
- [x] Add the author and the date.
- [x] Add short description.
- [x] Add link to the blog post.

**Screenshots**
![blogcard](https://github.com/202306-NEA-DZ-FEW/team-five/assets/107757609/02253ee0-9a58-4cdb-9699-4ba5dd852254)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2426-4814&mode=design&t=elut1LkjhOAi1bhH-4
