### ISSUE TITLE
Blog page component

### ISSUE THREAD

**Issue by DigitalDeveloperAM** [202306-NEA-DZ-FEW/team-five#46]
**Task title**
Blog page

**Task description**
Creating blog page with blog card can be showing, with all language files

**Subtasks**

- [x] Blog page component.
- [x] Hero image as in figma.
- [x] Add functionality of the blog card.

**Screenshots**
![blog](https://github.com/202306-NEA-DZ-FEW/team-five/assets/107757609/639063fa-47b1-45d7-b734-b82c14eebd4d)

**Link to the component on Figma**
[Put the link here](https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2426-4592&mode=design&t=elut1LkjhOAi1bhH-4)
