### ISSUE TITLE
Payment component 

### ISSUE THREAD

**Issue by mohamed70601** [202306-NEA-DZ-FEW/team-five#51]
**Task title**
Create payment component 

**Task description**
Create the payment information section 

**Subtasks**
- [ ] Implement a section for users to input their payment details 
- [ ] Integrate validation process to ensure the payment information provided by the user is correct 
- [ ] Include error handling to deal with issues like payment failures or incorrect information.
- [ ] Apply security measures for sensitive data protection
- [ ] Send an email receipt to the user's provided email address with a summary of the purchase

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/110736460/79f3e77a-9f2a-4bc3-adcc-77a608944855)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2439-7533&mode=design&t=dFJwWU7CXisxjEXB-0
