### ISSUE TITLE
Create a banner for coupons page

### ISSUE THREAD

**Issue by HamidAhmidat** [202306-NEA-DZ-FEW/team-five#59]
**Task title**
Create a banner  component for coupons page.
**Task description**
the banner is showing an image in the left side and a text description in the right.

**Subtasks**

- [x] Setup the coupons page.
- [x] Create banner as it is shown in the screenshot , and it must be responsive to all screens. 
- [ ] Create a test component for this banner.

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/137908128/67dc9280-227c-4caf-bfc9-3282d3d51035)

**Link to the component on Figma**
[Put the link here](https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2475-3134&mode=design&t=ITzc3pMXYib2W1bK-4)
