### ISSUE TITLE
Create Restaurants Cards

### ISSUE THREAD

**Issue by HamidAhmidat** [202306-NEA-DZ-FEW/team-five#61]
**Task title**
Create Restaurants Cards

**Task description**
This Component should have a card for every restaurant and the amount of money that is being sponsored by the coupons shown in the cards. Also, the sponsor will have the option of customizing the amount of money

**Subtasks**

- [x] create a restaurant card with a select button.
- [ ] fetch data from firestore. 
- [x] create add to cart button .
- [x] create custom input.
- [ ] make a responsive design for the cards.
- [ ] create the translation for  all the cards.
- [ ] create test component.

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/137908128/67a22102-1765-4ac5-87d3-eef533fc4c5a)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2968-3402&mode=design&t=ITzc3pMXYib2W1bK-4
