### ISSUE TITLE
Fetching Data to the blog

### ISSUE THREAD

**Issue by DigitalDeveloperAM** [202306-NEA-DZ-FEW/team-five#62]
**Task title**
Fetching date to The blog page

**Task description**
Fetching data in the blog card for food, hunger problems and donation news.

I add team member as the authors for every article random:
* Team member Photo
* Team member Full Name
* Date of the publishing article
* Short description of the article
* Fixing some Language Translation issues

**Subtasks**
- [x] Fetching data in the blog page.
- [x] Add member as author of the article
- [x] Enhancing the styles and the Rendering of the Components
- [x] Fixing Some issues.

**Screenshots**
