### ISSUE TITLE
Create CouponCard

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#66]
**Task title**
Create CouponCard

**Task description**
Design and implement a "CouponCard" component that displays information about coupons in a visually appealing and user-friendly way. This component will be used to present coupon details in a clear and engaging manner.

**Subtasks**
- [x] Design the layout and style of the "CouponCard"
- [x] Develop the "CouponCard" component to retrieve and display coupon information
- [x] Define the data and details to be shown on the card
- [x] Test the "CouponCard" component with sample coupon data

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/f11f7abe-e4e4-4b4b-a2a8-6795a27abcac)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2969-3426&mode=design&t=SrOFvQPS3tYYpOZv-4
