### ISSUE TITLE
style the coupons card

### ISSUE THREAD

**Issue by HamidAhmidat** [202306-NEA-DZ-FEW/team-five#84]
**Task title**
style the coupons card

**Task description**
styling the fetching cards. 

**Subtasks**

- [x] style the coupons card
- [x] style each coupon to be a card.
- [x] add a custom amount input
- [x] style add to cart button 

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/137908128/b4a95039-4d84-425c-a6e7-971cfbe03ed0)

**Link to the component on Figma**
(https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2968-3402&mode=design&t=k87ncT46TafanNNV-4)
