### ISSUE TITLE
Create Footer Component

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#9]
**Task title**
Create Footer Component

**Task description**
Design, create, and implement a responsive Footer component for the project, including necessary information and links.

**Subtasks**
- [x] Design the Footer layout
- [x] Implement responsive design
- [x] Include necessary information and links

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/136409213/63f5473b-0be2-4f92-a90d-28585815efaf)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=2321-4700&mode=design&t=LeCmaybhTbqQXYZh-4
