### ISSUE TITLE
Fix Home Page Style

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#90]
**Issue title**
Fix Home Page Style

**Issue description**
There is a styling issue on the home page that needs to be addressed. The page's appearance is not as intended or is inconsistent with the design specifications.

**Tasks**
- [x] Analyze the current CSS or styling code to understand the source of the problems
- [x] Develop solutions to fix the style issues
- [x] Apply the necessary CSS changes or improvements
- [x] Test the home page to confirm that the style issues have been resolved
- [x] Ensure that the home page is visually appealing
