### ISSUE TITLE
Fix Vercel problem with coupons page

### ISSUE THREAD

**Issue by HamidAhmidat** [202306-NEA-DZ-FEW/team-five#93]
**Task title**
Fix Vercel problem with coupons page

**Task description**
rewriting the code of the coupons page 

**Subtasks**

- [x] remove the first file of the coupons cards
- [x] create a new file of coupons card
- [x] rewrite the code

**Screenshots**

![Image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/137908128/0a166b85-2b1e-4a01-8988-c02ae4eca391)

**Link to the component on gitHub**
[Put the link here](https://github.com/202306-NEA-DZ-FEW/team-five/pull/88)
