### ISSUE TITLE
Fix: Blog page, blog container, navbar.

### ISSUE THREAD

**Issue by DigitalDeveloperAM** [202306-NEA-DZ-FEW/team-five#95]
**Task title**
Fixing Blog page, blog container, navbar

**Task description**
This is handling issues and bugs:
Blog Page: fixing issue of the style of the penner  that effect the footer, and fixing the Language changes.
Blog container: fixing issues to style and add Language files.
Navbar: fixing issue related to the responsivnes, adding drop down to the component and add drop down with flag to the language changes English and Algeria flag.

**Subtasks**
- [x] Issues to the penner (Blogpage).
- [x] Language changes (Blogpage).
- [x] Issues in the style (Blog container).
- [x] Adding Language files (Blog container).
- [x] Fixing responsive issue (Navbar)
- [x] Adding Language drop down (Navbar)
- [x] Adding Component drop down (Navbar).
