### ISSUE TITLE
Create Functionality for Payment Success Page

### ISSUE THREAD

**Issue by mohamed70601** [202306-NEA-DZ-FEW/team-five#97]
**Task title**
Create Functionality for Payment Success Page 

**Task description**
Turn payment success page into a functional and interactive page 

**Subtasks**
- [x] Display a noticeable animated green pass indicator and add "Thank You" message 
- [x] Add a Go Back button that turns the user back to the checkout page
- [x] Implement social sharing 
- [x] Incorporate translation
- [x] Make sure the page is responsive 

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/110736460/569f758e-fccb-45f5-90c9-dfda0e058de9)
![image](https://github.com/202306-NEA-DZ-FEW/team-five/assets/110736460/661bee99-ccbc-46d1-bc4d-fa9ba0c1bb71)

**Link to the component on Figma**
https://www.figma.com/file/hhlhVG4NPMRH8VfwE17MkO/capstone-team-library?type=design&node-id=3179-3402&mode=design&t=LROGJ5spJJ2BwDft-0
